
server:
  port: 8081

spring:
  application:
    name: ali-consumer-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #要和eureka注册服务的路径保持一致
feign:
  hystrix:
    enabled: true
